# Generated by Django 4.0.4 on 2022-05-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('coefficients', models.CharField(max_length=256, verbose_name='coefficients')),
                ('right_side', models.CharField(max_length=256, verbose_name='right_side')),
                ('segment_begin', models.IntegerField(verbose_name='segment_begin')),
                ('segment_end', models.IntegerField(verbose_name='segment-end')),
                ('step', models.FloatField(verbose_name='step')),
                ('init_conditions', models.CharField(max_length=256, verbose_name='init_conditions')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('numerical_solution', models.JSONField(verbose_name='num_sol')),
                ('graph_solution', models.CharField(max_length=256, verbose_name='graph_sol')),
                ('equation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.equation')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
